# Generated by Django 6.0.1 on 2026-01-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("slots_required", models.IntegerField(default=1)),
                ("min_level_required", models.IntegerField(default=1)),
                ("bonus_gold_cap", models.BooleanField(default=False)),
                ("bonus_member_slots", models.BooleanField(default=False)),
                ("bonus_healing", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Guild",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("level", models.IntegerField(default=1)),
                ("gxp", models.IntegerField(default=0)),
                (
                    "funds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("influence_points", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("PATENTED", "Patenteada"),
                            ("INDEPENDENT", "Independente"),
                            ("CLANDESTINE", "Clandestina"),
                        ],
                        default="INDEPENDENT",
                        max_length=20,
                    ),
                ),
                (
                    "moral_alignment",
                    models.CharField(
                        choices=[
                            ("HUMANITARIAN", "Humanitária"),
                            ("CORPORATE", "Corporativa"),
                            ("PREDATORY", "Predatória"),
                        ],
                        default="HUMANITARIAN",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuildBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("built_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guilda_manager.building",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_buildings",
                        to="guilda_manager.guild",
                    ),
                ),
            ],
        ),
    ]
