# Generated by Django 6.0.1 on 2026-01-28 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("DECEASED", "Deceased"),
                            ("INJURED", "Injured"),
                            ("RETIRED", "Retired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="guilda_manager.guild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[("EXTERNAL", "External"), ("INTERNAL", "Internal")],
                        default="EXTERNAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DELEGATED", "Delegated"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("DISASTER", "Disaster"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("duration_days", models.IntegerField(default=1)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("F", "F"),
                            ("E", "E"),
                            ("D", "D"),
                            ("C", "C"),
                            ("B", "B"),
                            ("A", "A"),
                            ("S", "S"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "gold_reward",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("gxp_reward", models.IntegerField(default=0)),
                (
                    "operational_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_quests",
                        to="guilda_manager.member",
                    ),
                ),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quests",
                        to="guilda_manager.guild",
                    ),
                ),
            ],
        ),
    ]
