# Generated by Django 6.0.1 on 2026-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0002_member_quest"),
    ]

    operations = [
        migrations.CreateModel(
            name="Monster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("size", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("monster_type", models.CharField(max_length=50)),
                ("combat_role", models.CharField(blank=True, max_length=100)),
                ("movement", models.CharField(blank=True, max_length=100)),
                ("defense", models.IntegerField(default=10)),
                ("habitat", models.CharField(blank=True, max_length=100)),
                (
                    "challenge_level",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("health_points", models.IntegerField(default=1)),
                ("weaknesses", models.TextField(blank=True)),
                ("immunities", models.TextField(blank=True)),
                ("special_abilities", models.TextField(blank=True)),
                ("image", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
