# Generated by Django 6.0.1 on 2026-02-10 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0003_monster"),
    ]

    operations = [
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("RECRUIT", "Recruta"),
                            ("CONFIRMED", "Confirmados"),
                            ("VETERAN", "Veteranos"),
                            ("ELITE", "Elite"),
                            ("LEGEND", "Lendas"),
                        ],
                        default="RECRUIT",
                        max_length=20,
                    ),
                ),
                ("missions_completed", models.IntegerField(default=0)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squads",
                        to="guilda_manager.guild",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("F", "F"),
                            ("E", "E"),
                            ("D", "D"),
                            ("C", "C"),
                            ("B", "B"),
                            ("A", "A"),
                            ("S", "S"),
                        ],
                        default="F",
                        max_length=2,
                    ),
                ),
                ("duration_days", models.IntegerField(default=1)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("COMPLETED", "Concluída"),
                            ("FAILED", "Falhou"),
                            ("DISASTER", "Desastre"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "result_log",
                    models.TextField(
                        blank=True,
                        help_text="Log of the resolution (roll, deaths, etc)",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatches",
                        to="guilda_manager.squad",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="member",
            name="squad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="guilda_manager.squad",
            ),
        ),
    ]
