# Generated by Django 6.0.1 on 2026-02-10 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0004_squad_dispatch_member_squad"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquadRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Rank Hierarchy Order (Lower is lower rank)",
                    ),
                ),
                ("missions_required", models.IntegerField(default=0)),
                ("min_guild_level", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="squad",
            name="rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="squads",
                to="guilda_manager.squadrank",
            ),
        ),
    ]
