# Generated by Django 6.0.1 on 2026-02-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0005_squadrank_alter_squad_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingPower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="powers",
                        to="guilda_manager.building",
                    ),
                ),
            ],
        ),
    ]
