# Generated by Django 4.2.9 on 2026-02-16 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0007_guild_code_guild_emblem_alter_building_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispatch",
            name="mission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="guilda_manager.quest",
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="npc_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F", "F"),
                    ("E", "E"),
                    ("D", "D"),
                    ("C", "C"),
                    ("B", "B"),
                    ("A", "A"),
                    ("S", "S"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="squad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="guilda_manager.squad",
            ),
        ),
    ]
