# Generated by Django 6.0.2 on 2026-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "guilda_manager",
            "0009_map_pin_alter_building_id_alter_buildingpower_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="background_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload map image",
                null=True,
                upload_to="guilda_manager/static/guilda_manager/maps/",
            ),
        ),
    ]
