# Generated by Django 6.0.2 on 2026-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0010_alter_map_background_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="map",
            name="background_image",
            field=models.ImageField(
                blank=True, help_text="Upload map image", null=True, upload_to="maps/"
            ),
        ),
    ]
