# Generated by Django 6.0.2 on 2026-02-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0011_alter_map_background_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="guild",
            name="party_q",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="guild",
            name="party_r",
            field=models.IntegerField(default=0),
        ),
    ]
