# Generated by Django 4.2.9 on 2026-03-03 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("guilda_manager", "0012_guild_party_q_guild_party_r"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("tier", models.IntegerField(default=1)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("icon", models.CharField(default="star", max_length=50)),
                (
                    "required_building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="guilda_manager.building",
                    ),
                ),
                (
                    "required_upgrade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_upgrades",
                        to="guilda_manager.upgrade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GuildUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guild",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guild_upgrades",
                        to="guilda_manager.guild",
                    ),
                ),
                (
                    "upgrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guilda_manager.upgrade",
                    ),
                ),
            ],
        ),
    ]
